# Generated by Django 5.2.1 on 2025-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_visualizationtype_alter_chat_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
